
package com.xumiao.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.ws.xumiao.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.xumiao.ws.client.User
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.ws.xumiao.com/UserService/getBlankUserRequest", output = "http://service.ws.xumiao.com/UserService/getBlankUserResponse")
    public User getBlankUser(
        @WebParam(name = "arg0", partName = "arg0")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.xumiao.ws.client.User
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.ws.xumiao.com/UserService/getUserRequest", output = "http://service.ws.xumiao.com/UserService/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.ws.xumiao.com/UserService/getUserInfoRequest", output = "http://service.ws.xumiao.com/UserService/getUserInfoResponse")
    public String getUserInfo(
        @WebParam(name = "arg0", partName = "arg0")
        User arg0);

}
