package com.xumiao.ws.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-13T16:55:42.205+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "UserServiceStub",
                  wsdlLocation = "http://localhost:8080/jaxb/services/UserService?wsdl",
                  targetNamespace = "http://localhost:8080/jaxb/services")
public class UserServiceStub extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080/jaxb/services", "UserSoapService");
    public final static QName UserServicePort = new QName("http://localhost:8080/jaxb/services", "UserServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/jaxb/services/UserService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserServiceStub.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/jaxb/services/UserService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserServiceStub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserServiceStub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServiceStub() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserServiceStub(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserServiceStub(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserServiceStub(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServicePort")
    public UserService getUserServicePort() {
        return super.getPort(UserServicePort, UserService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserService
     */
    @WebEndpoint(name = "UserServicePort")
    public UserService getUserServicePort(WebServiceFeature... features) {
        return super.getPort(UserServicePort, UserService.class, features);
    }

}
