package com.xumiao.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-13T16:55:42.170+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://localhost:8080/jaxb/services", name = "UserService")
@XmlSeeAlso({com.xumiao.ws.vo.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface UserService {

    @WebMethod
    @WebResult(name = "blankUser", targetNamespace = "http://localhost:8080/jaxb/services", partName = "blankUser")
    public com.xumiao.ws.vo.User getBlankUser(
        @WebParam(partName = "user", name = "user")
        com.xumiao.ws.vo.User user
    );

    @WebMethod
    @WebResult(name = "userInfo", targetNamespace = "http://localhost:8080/jaxb/services", partName = "userInfo")
    public java.lang.String getUserInfo(
        @WebParam(partName = "user", name = "user")
        com.xumiao.ws.vo.User user
    );

    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://localhost:8080/jaxb/services", partName = "user")
    public com.xumiao.ws.vo.User getUser(
        @WebParam(partName = "name", name = "name")
        java.lang.String name,
        @WebParam(partName = "age", name = "age")
        int age
    );
}
